version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: liar
      POSTGRES_PASSWORD: liarpass
      POSTGRES_DB: liardb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
infra: add postgres docker-compose
